{"uid":"65a407a519ebf07","name":"Delete taggal rendelkező poszt törlése","fullName":"vizsgaremek.automated_tests.test_conduit.TestPostHandling#testpostdelete","historyId":"6d2725dda7c5964827e67f33edd3e80d","time":{"start":1682252869250,"stop":1682252869250,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'vizsgaremek/test/datasource_users.csv'","statusTrace":"self = <test_conduit.TestPostHandling object at 0x7f429107c4f0>\n\n    def setup_method(self):\n        self.browser = chrome_driver_config()\n        self.browser.get('http://localhost:1667/#/login')\n>       for user in get_users_from_file():\n\nvizsgaremek/automated_tests/test_conduit.py:116: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_users_from_file():\n>       with open('vizsgaremek/test/datasource_users.csv', 'r', encoding='UTF-8') as datafile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'vizsgaremek/test/datasource_users.csv'\n\nvizsgaremek/automated_tests/main_functions.py:34: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestPostHandling","time":{"start":1682252869251,"stop":1682252870151,"duration":900},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'vizsgaremek/test/datasource_users.csv'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/python.py\", line 787, in _call_with_optional_argument\n    func()\n  File \"/home/runner/work/conduit/conduit/vizsgaremek/automated_tests/test_conduit.py\", line 116, in setup_method\n    for user in get_users_from_file():\n  File \"/home/runner/work/conduit/conduit/vizsgaremek/automated_tests/main_functions.py\", line 34, in get_users_from_file\n    with open('vizsgaremek/test/datasource_users.csv', 'r', encoding='UTF-8') as datafile:\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"as_id","value":"TC-08"},{"name":"parentSuite","value":"vizsgaremek.automated_tests"},{"name":"suite","value":"test_conduit"},{"name":"subSuite","value":"TestPostHandling"},{"name":"host","value":"fv-az349-463"},{"name":"thread","value":"3150-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"vizsgaremek.automated_tests.test_conduit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"65a407a519ebf07.json","parameterValues":[]}