{"uid":"a079e4fa20b7764d","name":"Sign up with valid data","fullName":"vizsgaremek.automated_tests.test_conduit.TestSignUp#test_sign_up_with_csv_valid","historyId":"e3f01b52edc6477f2c0d8db552c2c029","time":{"start":1682252863469,"stop":1682252863469,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'vizsgaremek/test/datasource_users.csv'","statusTrace":"self = <test_conduit.TestSignUp object at 0x7f4291e8ca90>\n\n    @allure.id(\"TC-01\")\n    @allure.title(\"Sign up with valid data\")\n    def test_sign_up_with_csv_valid(self):\n        wait = WebDriverWait(self.browser, 10)\n>       for user in get_users_from_file():\n\nvizsgaremek/automated_tests/test_conduit.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_users_from_file():\n>       with open('vizsgaremek/test/datasource_users.csv', 'r', encoding='UTF-8') as datafile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'vizsgaremek/test/datasource_users.csv'\n\nvizsgaremek/automated_tests/main_functions.py:34: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestSignUp","time":{"start":1682252861704,"stop":1682252863468,"duration":1764},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'vizsgaremek/test/datasource_users.csv'","statusTrace":"self = <test_conduit.TestSignUp object at 0x7f4291e8ca90>\n\n    @allure.id(\"TC-01\")\n    @allure.title(\"Sign up with valid data\")\n    def test_sign_up_with_csv_valid(self):\n        wait = WebDriverWait(self.browser, 10)\n>       for user in get_users_from_file():\n\nvizsgaremek/automated_tests/test_conduit.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_users_from_file():\n>       with open('vizsgaremek/test/datasource_users.csv', 'r', encoding='UTF-8') as datafile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'vizsgaremek/test/datasource_users.csv'\n\nvizsgaremek/automated_tests/main_functions.py:34: FileNotFoundError","steps":[],"attachments":[{"uid":"25220d43ca3057a6","name":"stderr","source":"25220d43ca3057a6.txt","type":"text/plain","size":159}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"_xunit_setup_method_fixture_TestSignUp::0","time":{"start":1682252863513,"stop":1682252863569,"duration":56},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"as_id","value":"TC-01"},{"name":"parentSuite","value":"vizsgaremek.automated_tests"},{"name":"suite","value":"test_conduit"},{"name":"subSuite","value":"TestSignUp"},{"name":"host","value":"fv-az349-463"},{"name":"thread","value":"3150-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"vizsgaremek.automated_tests.test_conduit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"a079e4fa20b7764d.json","parameterValues":[]}