{"uid":"1218a1644afe4be3","name":"Sign up with valid data","fullName":"vizsgaremek.test.test_conduit.TestSignUp#test_sign_up_with_csv_valid","historyId":"26366014dc4ac5038463c21fa035ef0f","time":{"start":1682094832978,"stop":1682094832978,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'","statusTrace":"self = <test_conduit.TestSignUp object at 0x7feab5c067d0>\n\n    @allure.id(\"TC-01\")\n    @allure.title(\"Sign up with valid data\")\n    def test_sign_up_with_csv_valid(self):\n        wait = WebDriverWait(self.browser, 2)\n>       for user in get_users_from_file():\n\nvizsgaremek/test/test_conduit.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_users_from_file():\n>       with open('datasource_users.csv', 'r', encoding='UTF-8') as datafile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'\n\nvizsgaremek/test/main_functions.py:37: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestSignUp","time":{"start":1682094825889,"stop":1682094832977,"duration":7088},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'","statusTrace":"self = <test_conduit.TestSignUp object at 0x7feab5c067d0>\n\n    @allure.id(\"TC-01\")\n    @allure.title(\"Sign up with valid data\")\n    def test_sign_up_with_csv_valid(self):\n        wait = WebDriverWait(self.browser, 2)\n>       for user in get_users_from_file():\n\nvizsgaremek/test/test_conduit.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_users_from_file():\n>       with open('datasource_users.csv', 'r', encoding='UTF-8') as datafile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'\n\nvizsgaremek/test/main_functions.py:37: FileNotFoundError","steps":[],"attachments":[{"uid":"2581d1c7b11cb3","name":"stderr","source":"2581d1c7b11cb3.txt","type":"text/plain","size":159}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"_xunit_setup_method_fixture_TestSignUp::0","time":{"start":1682094833023,"stop":1682094833080,"duration":57},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"as_id","value":"TC-01"},{"name":"parentSuite","value":"vizsgaremek.test"},{"name":"suite","value":"test_conduit"},{"name":"subSuite","value":"TestSignUp"},{"name":"host","value":"fv-az561-733"},{"name":"thread","value":"3079-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"vizsgaremek.test.test_conduit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"1218a1644afe4be3.json","parameterValues":[]}