{"uid":"aeae0b7f12b3470e","name":"Feedek címeinek listázása","fullName":"vizsgaremek.test.test_conduit.TestListOperations#test_listing_titles","historyId":"66869cdc6bd7f146b9feb2213f678c2d","time":{"start":1682228483337,"stop":1682228483337,"duration":0},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'","statusTrace":"self = <test_conduit.TestListOperations object at 0x7f4a9b743010>\n\n    def setup_method(self):\n        self.browser = chrome_driver_config()\n        self.browser.get('http://localhost:1667/#/login')\n>       for user in get_users_from_file():\n\nvizsgaremek/test/test_conduit.py:162: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_users_from_file():\n        #with open('vizsgaremek/test/datasource_users.csv', 'r', encoding='UTF-8') as datafile:\n>       with open('datasource_users.csv', 'r', encoding='UTF-8') as datafile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'\n\nvizsgaremek/test/main_functions.py:35: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestListOperations","time":{"start":1682228483337,"stop":1682228484243,"duration":906},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'\n","statusTrace":"  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/python.py\", line 907, in xunit_setup_method_fixture\n    _call_with_optional_argument(func, method)\n  File \"/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/_pytest/python.py\", line 787, in _call_with_optional_argument\n    func()\n  File \"/home/runner/work/conduit/conduit/vizsgaremek/test/test_conduit.py\", line 162, in setup_method\n    for user in get_users_from_file():\n  File \"/home/runner/work/conduit/conduit/vizsgaremek/test/main_functions.py\", line 35, in get_users_from_file\n    with open('datasource_users.csv', 'r', encoding='UTF-8') as datafile:\n","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":true,"hasContent":true}],"afterStages":[],"labels":[{"name":"as_id","value":"TC-10"},{"name":"parentSuite","value":"vizsgaremek.test"},{"name":"suite","value":"test_conduit"},{"name":"subSuite","value":"TestListOperations"},{"name":"host","value":"fv-az1030-985"},{"name":"thread","value":"3147-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"vizsgaremek.test.test_conduit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"aeae0b7f12b3470e.json","parameterValues":[]}