{"uid":"d41e45ff09656852","name":"Sign up with valid data","fullName":"vizsgaremek.test.test_conduit.TestSignUp#test_sign_up_with_csv_valid","historyId":"26366014dc4ac5038463c21fa035ef0f","time":{"start":1682228475396,"stop":1682228475397,"duration":1},"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'","statusTrace":"self = <test_conduit.TestSignUp object at 0x7f4a9c1d8280>\n\n    @allure.id(\"TC-01\")\n    @allure.title(\"Sign up with valid data\")\n    def test_sign_up_with_csv_valid(self):\n        wait = WebDriverWait(self.browser, 10)\n>       for user in get_users_from_file():\n\nvizsgaremek/test/test_conduit.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_users_from_file():\n        #with open('vizsgaremek/test/datasource_users.csv', 'r', encoding='UTF-8') as datafile:\n>       with open('datasource_users.csv', 'r', encoding='UTF-8') as datafile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'\n\nvizsgaremek/test/main_functions.py:35: FileNotFoundError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"_xunit_setup_method_fixture_TestSignUp","time":{"start":1682228473539,"stop":1682228475395,"duration":1856},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"testStage":{"status":"broken","statusMessage":"FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'","statusTrace":"self = <test_conduit.TestSignUp object at 0x7f4a9c1d8280>\n\n    @allure.id(\"TC-01\")\n    @allure.title(\"Sign up with valid data\")\n    def test_sign_up_with_csv_valid(self):\n        wait = WebDriverWait(self.browser, 10)\n>       for user in get_users_from_file():\n\nvizsgaremek/test/test_conduit.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def get_users_from_file():\n        #with open('vizsgaremek/test/datasource_users.csv', 'r', encoding='UTF-8') as datafile:\n>       with open('datasource_users.csv', 'r', encoding='UTF-8') as datafile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'datasource_users.csv'\n\nvizsgaremek/test/main_functions.py:35: FileNotFoundError","steps":[],"attachments":[{"uid":"8ed7830fa9ff9436","name":"stderr","source":"8ed7830fa9ff9436.txt","type":"text/plain","size":160}],"parameters":[],"stepsCount":0,"attachmentsCount":1,"shouldDisplayMessage":true,"hasContent":true},"afterStages":[{"name":"_xunit_setup_method_fixture_TestSignUp::0","time":{"start":1682228475438,"stop":1682228475493,"duration":55},"status":"passed","steps":[],"attachments":[],"parameters":[],"stepsCount":0,"attachmentsCount":0,"shouldDisplayMessage":false,"hasContent":false}],"labels":[{"name":"as_id","value":"TC-01"},{"name":"parentSuite","value":"vizsgaremek.test"},{"name":"suite","value":"test_conduit"},{"name":"subSuite","value":"TestSignUp"},{"name":"host","value":"fv-az1030-985"},{"name":"thread","value":"3147-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"vizsgaremek.test.test_conduit"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"d41e45ff09656852.json","parameterValues":[]}